# Default values for node-js.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dev
image: 064827688814.dkr.ecr.eu-west-3.amazonaws.com/test-repo-delete-dev:latest
