apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: delete
  name: delete
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: 064827688814.dkr.ecr.eu-west-3.amazonaws.com/test-repo-delete-dev:latest
    name: delete
  restartPolicy: Always