apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: delete
  name: delete
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image }}
    name: delete
  restartPolicy: Always