apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: delete
  name: my-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: delete